-- Finance app schema

create table if not exists public.profile (
  id bigint primary key default 1 check (id = 1),
  name text not null default '',
  currency text not null default 'INR',
  base_monthly_salary numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.income (
  id bigint generated by default as identity primary key,
  date date not null,
  type text not null check (type in ('Salary', 'Extra')) default 'Salary',
  source text not null default '',
  amount numeric not null default 0 check (amount >= 0),
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  date date not null,
  category text not null default '',
  description text not null default '',
  amount numeric not null default 0 check (amount >= 0),
  type text not null check (type in ('Fixed', 'Variable')) default 'Variable',
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  name text primary key,
  monthly_budget numeric null
);

create table if not exists public.savings_goals (
  month text primary key,
  target_amount numeric not null default 0 check (target_amount >= 0),
  notes text not null default ''
);

create table if not exists public.fixed_expenses (
  id bigint generated by default as identity primary key,
  name text not null default '',
  amount numeric not null default 0 check (amount >= 0),
  due_day int not null default 1 check (due_day between 1 and 31),
  category text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists income_date_idx on public.income (date);
create index if not exists expenses_date_idx on public.expenses (date);

-- RLS: personal finance app, single user. Enable and allow all for the
-- service role / authenticated app. Server-side API routes use the service
-- role key, which bypasses RLS, so these policies keep the table from being
-- wide-open if the anon key is ever used directly.
alter table public.profile enable row level security;
alter table public.income enable row level security;
alter table public.expenses enable row level security;
alter table public.categories enable row level security;
alter table public.savings_goals enable row level security;
alter table public.fixed_expenses enable row level security;

create policy "app access profile" on public.profile for all using (true) with check (true);
create policy "app access income" on public.income for all using (true) with check (true);
create policy "app access expenses" on public.expenses for all using (true) with check (true);
create policy "app access categories" on public.categories for all using (true) with check (true);
create policy "app access savings_goals" on public.savings_goals for all using (true) with check (true);
create policy "app access fixed_expenses" on public.fixed_expenses for all using (true) with check (true);

-- Grants: PostgREST (REST API) only exposes tables the anon/service_role
-- roles have privileges on, so the app's server-side client can read/write.
grant usage on schema public to anon, authenticated, service_role;

grant all on table public.profile to anon, authenticated, service_role;
grant all on table public.income to anon, authenticated, service_role;
grant all on table public.expenses to anon, authenticated, service_role;
grant all on table public.categories to anon, authenticated, service_role;
grant all on table public.savings_goals to anon, authenticated, service_role;
grant all on table public.fixed_expenses to anon, authenticated, service_role;

grant usage on sequence public.income_id_seq to anon, authenticated, service_role;
grant usage on sequence public.expenses_id_seq to anon, authenticated, service_role;
grant usage on sequence public.fixed_expenses_id_seq to anon, authenticated, service_role;

alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;
