-- Multi-user support.
--
-- - Adds a `users` table (username + password hash) powering per-user login.
-- - Re-scopes every data table to a user via `user_id`.
-- - Purges all existing rows: they are seed/demo ("fake") data from the
--   single-user setup, and accounts should start clean.
-- - Drops the now-unused `app_config` password-gate table and the leftover
--   empty `dummy-user` table.

create extension if not exists "pgcrypto";

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  username text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

drop table if exists public.fixed_expenses;
drop table if exists public.savings_goals;
drop table if exists public.categories;
drop table if exists public.expenses;
drop table if exists public.income;
drop table if exists public.profile;
drop table if exists public.app_config;
drop table if exists public."dummy-user";

create table public.profile (
  user_id uuid primary key references public.users(id) on delete cascade,
  name text not null default '',
  currency text not null default 'INR',
  base_monthly_salary numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table public.income (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  date date not null,
  type text not null check (type in ('Salary', 'Extra')) default 'Salary',
  source text not null default '',
  amount numeric not null default 0 check (amount >= 0),
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table public.expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  date date not null,
  category text not null default '',
  description text not null default '',
  amount numeric not null default 0 check (amount >= 0),
  type text not null check (type in ('Fixed', 'Variable')) default 'Variable',
  created_at timestamptz not null default now()
);

create table public.categories (
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  monthly_budget numeric null,
  primary key (user_id, name)
);

create table public.savings_goals (
  user_id uuid not null references public.users(id) on delete cascade,
  month text not null,
  target_amount numeric not null default 0 check (target_amount >= 0),
  notes text not null default '',
  primary key (user_id, month)
);

create table public.fixed_expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null default '',
  amount numeric not null default 0 check (amount >= 0),
  due_day int not null default 1 check (due_day between 1 and 31),
  category text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists income_user_date_idx on public.income (user_id, date);
create index if not exists expenses_user_date_idx on public.expenses (user_id, date);
create index if not exists fixed_expenses_user_idx on public.fixed_expenses (user_id);

alter table public.users enable row level security;
alter table public.profile enable row level security;
alter table public.income enable row level security;
alter table public.expenses enable row level security;
alter table public.categories enable row level security;
alter table public.savings_goals enable row level security;
alter table public.fixed_expenses enable row level security;

-- Server-side API routes use the service-role key (bypasses RLS). No grants
-- for anon/authenticated, matching the harden_security migration.
grant usage on schema public to service_role;

grant all on table public.users, public.profile, public.income, public.expenses,
  public.categories, public.savings_goals, public.fixed_expenses
  to service_role;

grant usage on sequence public.income_id_seq to service_role;
grant usage on sequence public.expenses_id_seq to service_role;
grant usage on sequence public.fixed_expenses_id_seq to service_role;

alter default privileges in schema public grant all on tables to service_role;
alter default privileges in schema public grant all on sequences to service_role;
